global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'account'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['account:8082']
  - job_name: 'shop'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['shop:8081']
  - job_name: 'notification'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['notification:8084']
  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['order:8083']
  - job_name: 'keycloakrestapi'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['keycloakrestapi:8085']
