services:
  mysql:
    image: phucxmysql:1.0.0
    container_name: mysql
    ports:
      - 3305:3306
    volumes:
      - D:\thuchanh\sts\docker-storage\mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=10122003simp!simp
    networks:
      - phucx

  keycloak:
    image: phucxkeycloak:2.0.0
    container_name: keycloak
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - WAIT_FOR_DATABASE=true
      - KC_DB=mysql
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=123
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=10122003simp!simp
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
    networks:
      - phucx

  redis:
    image: redis:7.2-alpine
    container_name: redis
    stdin_open: true 
    tty: true 
    ports:
      - 6379:6379
    networks:
      - phucx

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine
    container_name: oauth2-proxy
    command:
      - --http-address
      - 0.0.0.0:4180
    restart: always
    depends_on:
      - redis
      - keycloak
    ports:
      - 4180:4180
    environment:
      - OAUTH2_PROXY_PROVIDER=keycloak-oidc
      - OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=Keycloak
      - OAUTH2_PROXY_CLIENT_ID=b7afe9b7-6c53-44a1-8e76-bff80f45bead
      - OAUTH2_PROXY_CLIENT_SECRET=BFiwf7shEhqNNPcLLFaaBwB8oiVStDAi

      - OAUTH2_PROXY_LOGIN_URL=http://localhost:8080/realms/master/protocol/openid-connect/auth
      - OAUTH2_PROXY_REDEEM_URL=http://keycloak:8080/realms/master/protocol/openid-connect/token
      - OAUTH2_PROXY_OIDC_JWKS_URL=http://keycloak:8080/realms/master/protocol/openid-connect/certs

      - OAUTH2_PROXY_BACKEND_LOGOUT_URL=http://keycloak:8080/realms/master/protocol/openid-connect/logout?post_logout_redirect=http://localhost:5173&id_token_hint={id_token}
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://localhost:8080/realms/master
      - OAUTH2_PROXY_GRANT_TYPE=authorization_code
      - OAUTH2_PROXY_SCOPE=openid

      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_WHITELIST_DOMAINS=localhost:8060,localhost:5173,localhost:8080,keycloak:8080
      
      - OAUTH2_PROXY_COOKIE_SECRET=fLIblJsthbMhgELnmpqrCbWQD9P1vyDfI5SAs8BUG6c=
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_COOKIE_REFRESH=2m
      - OAUTH2_PROXY_COOKIE_EXPIRE=10m
      - OAUTH2_PROXY_COOKIE_HTTPONLY=true
      - OAUTH2_PROXY_COOKIE_NAME=SESSION

      - OAUTH2_PROXY_SKIP_OIDC_DISCOVERY=true
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true

      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true

      - OAUTH2_PROXY_SESSION_STORE_TYPE=redis
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://redis:6379
    networks:
      - phucx

  rabbitmq:
    image: phucxrabbitmq:1.0.0
    container_name: phucxfoodmq
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    networks:
      - phucx
  
  keycloakrestapi:
    image: phucxkeycloakrestapi:2.0.0
    ports:
      - 8085:8085
    container_name: keycloakrestapi
    depends_on:
      - rabbitmq
      - keycloak
    restart: unless-stopped
    environment:
      - WAIT_FOR_DATABASE=true
      - KEYCLOAK_RESTAPI_DEV_URL=http://localhost:8085
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_PASSWORD=123
      - KEYCLOAK_CLIENT_ID=b7afe9b7-6c53-44a1-8e76-bff80f45bead
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=123
    networks:
      - phucx

  shop:
    image: shop:2.0.0
    ports:
      - 8081:8081
    container_name: shop
    volumes:
      - D:\thuchanh\sts\docker-storage\image\product:/usr/src/app/image/product
      - D:\thuchanh\sts\docker-storage\image\category:/usr/src/app/image/category
    depends_on:
      - mysql
      - rabbitmq
      - keycloak
      - redis
    restart: unless-stopped
    environment:
      - WAIT_FOR_DATABASE=true
      - SHOP_DEV_URL=http://localhost:8081
      - CONFIG_URL=http://configserver:8071
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - KEYCLOAK_ISSUER _URI=http://keycloak:8080/realms/master
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=123
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=10122003simp!simp
      - MYSQL_URL=jdbc:mysql://mysql:3306/product
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - phucx

  account:
    image: account:2.0.0
    ports:
      - 8082:8082
    container_name: account
    volumes:
      - D:\thuchanh\sts\docker-storage\image\customer:/usr/src/app/image/customer
      - D:\thuchanh\sts\docker-storage\image\employee:/usr/src/app/image/employee
    depends_on:
      - mysql
      - rabbitmq
      - keycloak
      - redis
    restart: unless-stopped
    environment:
      - WAIT_FOR_DATABASE=true
      - ACCOUNT_DEV_URL=http://localhost:8082
      - CONFIG_URL=http://configserver:8071
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=123
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=10122003simp!simp
      - MYSQL_URL=jdbc:mysql://mysql:3306/profile
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TWILIO_CLIENT_ID={TWILIO_CLIENT_ID}
      - TWILIO_CLIENT_SECRET={TWILIO_CLIENT_SECRET}
      - TWILIO_SERVICE_SID={TWILIO_SERVICE_SID}
    networks:
      - phucx
  
  notification:
    image: notification:2.0.0
    container_name: notification
    ports:
      - 8084:8084
    depends_on:
      - keycloak
      - rabbitmq
    restart: unless-stopped
    environment:
      - WAIT_FOR_DATABASE=true
      - NOTIFICATION_DEV_URL=http://localhost:8084
      - CONFIG_URL=http://configserver:8071
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=123
      - RABBITMQ_STOMP_PORT=61613
      - UI_URL=http://localhost:5173
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=10122003simp!simp
      - MYSQL_URL=jdbc:mysql://mysql:3306/notification
    networks:
      - phucx

  order:
    image: order:2.0.0
    ports:
      - 8083:8083
    container_name: order
    depends_on:
      - redis
      - mysql
      - rabbitmq
      - keycloak
    restart: unless-stopped
    environment:
      - WAIT_FOR_DATABASE=true
      - ORDER_DEV_URL=http://localhost:8083
      - CONFIG_URL=http://configserver:8071
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=123
      - REDIRECT_PAYMENT_URL=http://localhost:8086
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=10122003simp!simp
      - MYSQL_URL=jdbc:mysql://mysql:3306/order
    networks:
      - phucx

  payment:
    image: payment:1.0.0
    container_name: payment
    ports:
      - 8086:8086
    depends_on:
      - keycloak
      - mysql
      - rabbitmq
    environment:
      - WAIT_FOR_DATABASE=true
      - PAYPAL_CLIENT_ID={PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET={PAYPAL_CLIENT_SECRET}
      - PAYPAL_MODE=sandbox
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=10122003simp!simp
      - MYSQL_URL=jdbc:mysql://mysql:3306/payment
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=123
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - PAYMENT_SUCCESSFUL_URL=http://localhost:5173/order?status=successful
      - PAYMENT_CANCELED_URL=http://localhost:5173/order?status=canceled
    networks:
      - phucx
    
  prometheus:
    image: phucxprometheus:1.0.0
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - phucx
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    restart: unless-stopped
    networks: 
      - phucx

  gateway:
    image: phucxnginx:2.0.0
    ports:
      - 8060:8060
    container_name: nginx
    depends_on:
      - shop
      - account
      - keycloakrestapi
      - notification
      - order
      - oauth2-proxy
    restart: unless-stopped
    environment:
      - OAUTH2_PROXY=http://oauth2-proxy:4180
      - SHOP_URL=http://shop:8081
      - ACCOUNT_URL=http://account:8082 
      - PAYMENT_URL=http://payment:8086
      - ORDER_URL=http://order:8083
      - NOTIFICATION_URL=http://notification:8084
      - AUTHORIZATION_URL=http://keycloakrestapi:8085
      - REDIRECT_UI=http://localhost:5173
      - ALLOWED_ORIGIN=http://localhost:5173
      - KEYCLOAK_USER_URL=http://localhost:8080/realms/master/account/
      - KEYCLOAK_ADMIN_URL=http://localhost:8080/admin/master/console/
    networks:
      - phucx

  foodshopui:
    image: foodshopui:1.0.0
    container_name: foodshopui
    ports:
      - 5173:80
    environment:
      - PHUCX_API_URL=http://localhost:8060
    networks:
      - phucx

networks:
  phucx: