version: '3.8'

services:
  sql:
    image: phucxsqlserver:1.0.0
    container_name: sqlserver
    ports:
      - 1431:1433
    stdin_open: true 
    tty: true 
    volumes:
      - D:\thuchanh\sts\docker-storage\sqlserver:/var/opt/mssql/data
    networks:
      - phucx

  keycloak:
    image: phucxkeycloak:1.0.0
    container_name: phucxkeycloak
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - sql
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=123
    networks:
      - phucx

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - phucx

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine
    container_name: oauth2-proxy
    command:
      - --http-address
      - 0.0.0.0:4180
    restart: always
    depends_on:
      - redis
      - keycloak
    ports:
      - 4180:4180
    environment:
      - OAUTH2_PROXY_PROVIDER=keycloak-oidc
      - OAUTH2_PROXY_PROVIDER_DISPLAY_NAME=Keycloak
      - OAUTH2_PROXY_CLIENT_ID=803e434f-c3a8-436f-a200-8b959476efdc
      - OAUTH2_PROXY_CLIENT_SECRET=mXIR4h0hsghL1DtwnmPY4jHpoKrnJ3gk
      - OAUTH2_PROXY_LOGIN_URL=http://localhost:8080/realms/master/protocol/openid-connect/auth
      - OAUTH2_PROXY_REDEEM_URL=http://keycloak:8080/realms/master/protocol/openid-connect/token
      - OAUTH2_PROXY_OIDC_JWKS_URL=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - OAUTH2_PROXY_BACKEND_LOGOUT_URL=http://keycloak:8080/realms/master/protocol/openid-connect/logout?post_logout_redirect=http://localhost:5173&id_token_hint={id_token}
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://keycloak:8080/realms/master
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://localhost:8080/realms/master
      - OAUTH2_PROXY_GRANT_TYPE=authorization_code
      - OAUTH2_PROXY_SCOPE=openid

      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_WHITELIST_DOMAINS=localhost:8060,localhost:5173,localhost:8080,keycloak:8080
      
      - OAUTH2_PROXY_COOKIE_SECRET=fLIblJsthbMhgELnmpqrCbWQD9P1vyDfI5SAs8BUG6c=
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_COOKIE_REFRESH=30m
      - OAUTH2_PROXY_COOKIE_HTTPONLY=true
      - OAUTH2_PROXY_COOKIE_NAME=SESSION

      - OAUTH2_PROXY_SKIP_OIDC_DISCOVERY=true
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true

      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true


      - OAUTH2_PROXY_SESSION_STORE_TYPE=redis
      - OAUTH2_PROXY_REDIS_CONNECTION_URL=redis://redis:6379
    networks:
      - phucx

  rabbitmq:
    image: phucxrabbitmq:1.0.0
    container_name: phucxfoodmq
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    networks:
      - phucx

  # configserver:
  #   image: configserver:1.0.0
  #   ports:
  #     - 8071:8071
  #   restart: unless-stopped
  #   container_name: configserver
  #   networks:
  #     - phucx


  keycloakrestapi:
    image: phucxkeycloakrestapi:1.0.0
    ports:
      - 8085:8085
    container_name: keycloakrestapi
    depends_on:
      - rabbitmq
      - keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_PASSWORD=123
      - KEYCLOAK_CLIENT_ID=803e434f-c3a8-436f-a200-8b959476efdc
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - RABBITMQ_HOST=rabbitmq
    networks:
      - phucx

  shop:
    image: shop:1.0.0
    ports:
      - 8081:8081
    container_name: shop
    volumes:
      - D:\thuchanh\sts\docker-storage\image\product:/usr/src/app/image/product
      - D:\thuchanh\sts\docker-storage\image\category:/usr/src/app/image/category
    depends_on:
      - sql
      - rabbitmq
      - keycloak
      - redis
    restart: unless-stopped
    environment:
      - CONFIG_URL=http://configserver:8071
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - KEYCLOAK_ISSUER _URI=http://keycloak:8080/realms/master
      - RABBITMQ_HOST=rabbitmq
      - SQL_USERNAME=sa
      - SQL_PASSWORD=10122003simp!simp
      - SQL_URL=jdbc:sqlserver://sql:1433;database=product;encrypt=true;trustServerCertificate=true
      - PRODUCT_IMAGE_LOCATION=/usr/src/app/image/product
      - CATEGORY_IMAGE_LOCATION=/usr/src/app/image/category
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - phucx
  
  account:
    image: account:1.0.0
    ports:
      - 8082:8082
    container_name: account
    volumes:
      - D:\thuchanh\sts\docker-storage\image\customer:/usr/src/app/image/customer
      - D:\thuchanh\sts\docker-storage\image\employee:/usr/src/app/image/employee
    depends_on:
      - sql
      - rabbitmq
      - keycloak
      - redis
    restart: unless-stopped
    environment:
      - CONFIG_URL=http://configserver:8071
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - RABBITMQ_HOST=rabbitmq
      - SQL_USERNAME=sa
      - SQL_PASSWORD=10122003simp!simp
      - SQL_URL=jdbc:sqlserver://sql:1433;database=profile;encrypt=true;trustServerCertificate=true
      - CUSTOMER_IMAGE_LOCATION=/usr/src/app/image/customer
      - EMPLOYEE_IMAGE_LOCATION=/usr/src/app/image/employee
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - phucx
  
  notification:
    image: notification:1.0.0
    container_name: notification
    ports:
      - 8084:8084
    depends_on:
      - keycloak
      - rabbitmq
    restart: unless-stopped
    environment:
      - CONFIG_URL=http://configserver:8071
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - RABBITMQ_HOST=rabbitmq
      - SQL_USERNAME=sa
      - SQL_PASSWORD=10122003simp!simp
      - SQL_URL=jdbc:sqlserver://sql:1433;database=notification;encrypt=true;trustServerCertificate=true
    networks:
      - phucx

  order:
    image: order:1.0.0
    ports:
      - 8083:8083
    container_name: order
    depends_on:
      - redis
      - sql
      - rabbitmq
      - keycloak
    restart: unless-stopped
    environment:
      - CONFIG_URL=http://configserver:8071
      - KEYCLOAK_JWK_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs
      - RABBITMQ_HOST=rabbitmq
      - SQL_USERNAME=sa
      - SQL_PASSWORD=10122003simp!simp
      - SQL_URL=jdbc:sqlserver://sql:1433;database=order;encrypt=true;trustServerCertificate=true
    networks:
      - phucx
    
  prometheus:
    image: phucxprometheus:1.0.0
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - phucx
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    restart: unless-stopped
    networks: 
      - phucx

  gateway:
    image: phucxnginx:1.0.0
    ports:
      - 8060:8060
    container_name: nginx
    depends_on:
      - keycloak
      - shop
      - account
    restart: unless-stopped
    environment:
      - OAUTH2_PROXY=http://oauth2-proxy:4180
      - SHOP_URL=http://shop:8081
      - ACCOUNT_URL=http://account:8082 
      - ORDER_URL=http://order:8083
      - NOTIFICATION_URL=http://notification:8084
      - AUTHORIZATION_URL=http://keycloakrestapi:8085
      - REDIRECT_UI=http://localhost:5173
      - ALLOWED_ORIGIN=http://localhost:5173
      - KEYCLOAK_USER_URL=http://localhost:8080/realms/master/account/
      - KEYCLOAK_ADMIN_URL=http://localhost:8080/admin/master/console/
    networks:
      - phucx

networks:
  phucx: